### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by futzlarson** [greghub/green-audio-player#10]
Love the player, planning to use it for my startup. I think it would really gain some traction if you added options to customize the interface like colors and hiding elements. In the meantime, this is the CSS I'm using to accomplish this:

```
audio, .green-audio-player .volume, .controls .controls__current-time, .controls .controls__total-time {
    display: none;
}
.green-audio-player .controls .controls__slider {
    margin-right: 0;
}
.green-audio-player {
    background-color: transparent;
    box-shadow: none;
    height: auto;
    padding: 0;
}
.green-audio-player .controls {
    margin-left: 10px;
    margin-right: 0;
}
.green-audio-player .slider .gap-progress, .green-audio-player .slider .gap-progress .progress__pin {
    background-color: $yellow;
}
```

I'm not immediately seeing how to customize the play/pause button color (you might need to set `fill` on SVG inline IIRC?). So this is what I'm thinking:

- Hide elements and their margins
- Disable padding/height/box-shadow
- Customize colors (icons, timeline) as well as size (particularly play/pause, timeline dot and the player width itself)
- Option for transparent background

To give you context for what this lets me do:

![image](https://user-images.githubusercontent.com/1168673/59713037-739ccf80-91dc-11e9-956d-184432d7102c.png)

Also an example of said options in the README would be great. I assume you pass an object, but it's not stated explicitly.

**Comment by greghub** [comment]
Hi @futzlarson all the customizations are actually meant to be done with CSS. And yes the play pause button color can be customized with CSS as well:
```css
.play-pause-btn svg path {
    fill: red;
}
```

**Comment by futzlarson** [comment]
I get that - it's what CSS is for - but it actually took me a little while to figure out exactly what I needed to customize it. Maybe a guide to customizing?

**Comment by greghub** [comment]
Styling of the component shall be done using CSS. If it's a specific case where it is not possible please reopen the issue
