### ISSUE TITLE
modified the player with your permission

### ISSUE THREAD

**Issue by tnbnicer** [greghub/green-audio-player#12]
Hi GregHub,
Congratulation on a terrific simple audio player.

I've had concerns about using MediaElementPlayer because of the overhead. (How to reduce it?) It is of course an audio and video player, a WordPress, Facebook. Dailymotion, Flash, Silverlight, Vimeo, YouTube, etc. plugin, and the overhead is enormous, even without JQuery.

I like Green Audio Player a lot, so much so that I made it my own so to speak. In the course of my taking ownership (so to speak), I made some additions and also reductions, that I think are relevant and may also be interesting. I more or less retain the GitHub structure (/build and /src folders), although -- don't worry -- I don't plan on starting a rival project. I would like to share the modified code, if I can link it somewhere in a Zip file.

Would you be interested and would that be okay with you?

I could post a link here that points to my site, but I believe that's unfair promotion. Does GitHub have an anonymous mailbox for contacting you?

Among my changes is that I generate the Html with PHP. The JS template is disabled, but it is still part of the code (if needed). 

Best,
Tom

**Comment by tnbnicer** [comment]
Created a fork at:

https://github.com/tnbnicer/green-audio-player

I hope this is usable.

**Comment by tnbnicer** [comment]
Sources (test):
../dist/css/green-audio-player.css
../dist/css/green-audio-player.min.css
../dist/js/green-audio-player.js
../dist/js/green-audio-player.min.js
../examples/single-instance-2.html
../examples/audio/example-1.mp3

Added: Up/Down arrows (volume)
Added: Left/Right arrows (seek)
Added: Spacebar (play/pause)
Added: Loop icon
Added: aria
Added: tabindexes
Added: spinner container

Removed: stopOtherPlayers
Removed: directionAware

Changed: svgs
Changed: smaller

**Comment by greghub** [comment]
@tnbnicer thank you very much for your interest and your work. If you want these changes to become a part of Green Audio Player please open a "Pull Request" and we'll see if they can be merged. I want to preserve "stopOtherPlayers" and "directionAware" features, but I'm really interested in the accessibility features.

**Comment by tnbnicer** [comment]
@greghub It's proving rather challenging to integrate accessibility with OtherPlayers. I can't promise anything, but I will spend some time on it.

**Comment by greghub** [comment]
Hi @tnbnicer is it possible to create a pull request that would include the following of your changes:
Added: Up/Down arrows (volume)
Added: Left/Right arrows (seek)
Added: Spacebar (play/pause)
Added: Loop icon
Added: aria
Added: tabindexes
Added: spinner container

Those would be a great addition to the library

**Comment by tnbnicer** [comment]
Yes. A pull request is possible.

There are two possibilities. A) Merging the players and B) Keepig them as separate libraries.

B) As an example, I would create a fork from yours, and add:

dist/js/green-audio-player-two.js
dist/css/green-audio-player-two.css
examples/single-instance-two.js
src/js/main-two.js
src/scss/main-two.scss

And append a section to the README.md file with a description.

A) Accessibility features don't work that well with multiple-instance players. You can put them in the code, but I recommend disabled for when the user has more than one player on a page.

C) The spinner container is CSS and a few extra boxes. If you want, I can add it to the main player, regardless of A) or B).

Let me know which method you prefer. (I prefer B, perhaps C.) Any other suggestions would be welcome as well.

**Comment by tnbnicer** [comment]
Hi @**greghub**

I uploaded all the pull request files. I hope you like it. It's a big request. Thanks.

**Comment by greghub** [comment]
Approved and merged! The changes are available in version `1.1.0`
