### ISSUE TITLE
play button not displayed with preload="none"

### ISSUE THREAD

**Issue by tyctor** [greghub/green-audio-player#16]
hi 
i am trying to use your player with `<audio preload="none">`
`preload="none"` causes that play button never shows because of loading spinner

it seems that calling
`this.hideLoadingIndicator();`
in GreenAudioPlayer object constructor resolves this issue

also i have question if could be possible to play mp3 file which is splited into chunks

**Comment by greghub** [comment]
@tyctor fixed in version `1.1.1`, thanks to a contribution from @tnbnicer !
