### ISSUE TITLE
playPauseBtn on autoplay

### ISSUE THREAD

**Issue by swebsoft** [greghub/green-audio-player#17]
I love this player, but when set to autoplay the playPauseBtn does not change to show pause icon. I also can't find option to change playPauseBtn and Volume button colors, can change volume button color when clicked.

**Comment by greghub** [comment]
Hi @swebsoft , thank you for raising the issue. It is fixed in `1.0.14`
For changing the color of the buttons use css to set a `fill` property on the `path`. For example:
```
.play-pause-btn__icon {
  fill: red;
}
```
