### ISSUE TITLE
no coding old guy doesn't get what it wants on his site

### ISSUE THREAD

**Issue by Uncleeti** [greghub/green-audio-player#18]
Hello, 
I arrive here because so far I could not get any help with this. 
I am building with Wbuilder a site where I use quite a lot of GAPlayers. In fact I upgraded because I wanted to subsitute GAPlayer to HTML5 player for the sake of responsivity and esthetic too. 
But the fact is it doesn't display well with layout grids, which is what I use. 
Overlapping, dimension not symetrical to other objects of the page. 
You would be so kind if you could have a look and tell me what you see is wrong (hoping I understand!). Some examples
 
https://www.khenpo.fr/dent_blanche.html

https://www.khenpo.fr/chant-de-sahara.html

Also, in mobile portable -at least my old Iphone 4s- it doesn't look good either. Missing a piece or this kind of thing. 
I sus pect GAPlayer was not designed for layout grids. So, be kind enough to tell me how I should use, taking into account my project. 

Thank you for your time.

**Comment by greghub** [comment]
Hi @Uncleeti I'll be more than happy to help you. I have noticed two problems:
1) The audio file cannot be loaded. Which is not related to the Green Audio Player. The filename is probably incorrect (try using "-" or "_" instead of space in the filename) and make sure the file URL is correct. At the moment it cannot load the audio file.

2) Element with ID *wb_Chant-de-saharaExtension1* has a a "display: inline-block" property. That overwrites the display behavior of GAPlayer. If you remove the "display: inline-block" it will be visually correct.

Please try that and let me if your issue is resolved and I'll try to help if there's still a problem

**Comment by Uncleeti** [comment]
Hello, 
Don't pay attention to the sound missing ; I did not put any for minimizing your downloading time. 
Otherwise, I removed the "display: inline-block" but as you can see it still doesn't fit the same size as the above layout. (Tks to check my html ; I am not good at all in coding  but I think it's right!)

Thank you so much for your help, anyway.

Eti

**Comment by Uncleeti** [comment]
Oups, I check and inline-block is there. Sorry ! The problem is I work with Webbuilder and apparently the properties of Wb css overwrite my own corrected css? I have to ask how to change that first.

**Comment by greghub** [comment]
@Uncleeti I have changed a few things in GAP, so that it's harder to overwrite some of it's properties. If you download the latest version, it will not have that problem

**Comment by Uncleeti** [comment]
I have downloaded the extension on this one page here , and substituted all these downloaded files  to the previous one in web builder/system/extensions file but I don't see any difference.

**Comment by greghub** [comment]
@Uncleeti I have checked your page and it is not using the latest version. Consider loading it from the CDN to make sure you always have the most recent version:

You can include the tags in the HTML if your editor allows it:

```
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/greghub/green-audio-player/dist/css/green-audio-player.min.css">
<script src="https://cdn.jsdelivr.net/gh/greghub/green-audio-player/dist/js/green-audio-player.min.js"></script>
```

**Comment by Uncleeti** [comment]
Hi Greghub, 
I am sorry but I could not do much of your advice, because, as the title of the topic says, I don't know how to code (actually a bit of HTML 4.0 transitionnal, which I learned for some pages, but it's like me, an old story.)
On the other end, I asked some help to Webbuilder support team, ("Marco" as they sign). I fell on the person who added your GAP to wbebuilding and he/she kindly said -because GAP is provided without support, so it's kind of him- he would do what you recommanded to me when he/she will have time. So, your advice was not lost, and me I will have a solution sooner or later. 
So it's OK ! :) 
Thank again.

**Comment by greghub** [comment]
@Uncleeti great, once they do those steps, the issue will be fixed
