### ISSUE TITLE
Hide volume control?

### ISSUE THREAD

**Issue by StephenMeehan2016** [greghub/green-audio-player#20]
Hi

Would it be possible to add an option to hide the volume control via the script?

**Comment by greghub** [comment]
Hi @StephenMeehan2016 thanks for opening the issue. It is easily possible to do using CSS by adding
```
.volume { display: none; }
```

Is there a specific case where this solution doesn't work?

**Comment by greghub** [comment]
Please re-open if the solution doesn't work
