### ISSUE TITLE
audio scrub seems bugged on different site widths. 

### ISSUE THREAD

**Issue by Mminner4248** [greghub/green-audio-player#3]
Hello there, 

Really love the work you've done on this audio player. I've had issues with the horizontal not working when the width of the window changes. While it works fine on my macbook, my monitors don't seem to work. I'm assuming it has something to do with the offsetLeft function? Have you run into any issues like this?

**Comment by greghub** [comment]
@Mminner4248 Hi, thanks a lot for your interest and for submitting an issue. I looked into it, but unfortunately I could not reproduce the problem. Does that happen when you resize the browser window? or when your browser is on the external monitor? Also what browser are you trying it on?

**Comment by Mminner4248** [comment]
It occurs when the browser width changes. I'm currently working on Chrome Version 71.0.3578.98. While working on the audio player, we noticed it would work on the external monitor with the dev console open, but then stop as soon as it closed. No refresh required. The current mp3 file paths are somewhat long, around 9 minutes, but many will get up to 40 minutes in length.

**Comment by greghub** [comment]
@Mminner4248 today I had a chance to try it on an external monitor, but still couldn't reproduce the issue. Do you receive any errors in the console? Are there other scripts on the page that could conflict with the library?

**Comment by Mminner4248** [comment]
That's a great question. We are curious if it is breaking because of the foundation styling classes. We are going to dig a little deeper and see what we can come up with. I appreciate you looking into it.
