### ISSUE TITLE
Volume strings technical details

### ISSUE THREAD

**Issue by diemax** [greghub/green-audio-player#7]
```js
updateVolume() {
        this.volumeProgress.style.height = `${this.player.volume * 100}%`;
        if (this.player.volume >= 0.5) {
            this.speaker.attributes.d.value = 'M14.667 0v2.747c3.853 1.146 6.666 4.72 6.666 8.946 0 4.227-2.813 7.787-6.666 8.934v2.76C20 22.173 24 17.4 24 11.693 24 5.987 20 1.213 14.667 0zM18 11.693c0-2.36-1.333-4.386-3.333-5.373v10.707c2-.947 3.333-2.987 3.333-5.334zm-18-4v8h5.333L12 22.36V1.027L5.333 7.693H0z';
        } else if (this.player.volume < 0.5 && this.player.volume > 0.05) {
            this.speaker.attributes.d.value = 'M0 7.667v8h5.333L12 22.333V1L5.333 7.667M17.333 11.373C17.333 9.013 16 6.987 14 6v10.707c2-.947 3.333-2.987 3.333-5.334z';
        } else if (this.player.volume <= 0.05) {
            this.speaker.attributes.d.value = 'M0 7.667v8h5.333L12 22.333V1L5.333 7.667';
        }
    }
```

Hi, how are you? First thing first, great project! :smile:
I have a question for you, where can I find some documentation related to those strings you are using?
I'd like to create a React version of this player, and reading the code I came across this values which I couldn't find any details about them yet.

Thanks!

**Comment by greghub** [comment]
Hi @diemax , thank you!
It would be great if there's a React version as well!

Those string are changing the speaker icon, as you increase or decrease volume. Notice that the speaker icon has 3 versions: loud, quiet and muted.

Those strings are SVG codes for the paths that draw the speaker icon. It's a piece of inline SVG code, so the strings are static, you can simply copy them.

I then set the value of the "d" attribute of the path element here:

```html
<div class="volume-btn open">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path fill="#566574" fill-rule="evenodd" d="M0 7.667v8h5.333L12 22.333V1L5.333 7.667M17.333 11.373C17.333 9.013 16 6.987 14 6v10.707c2-.947 3.333-2.987 3.333-5.334z"></path>
    </svg>
</div>
```

In React you could simply use something like:

```jsx
<path fill="#566574" fill-rule="evenodd" d="{this.speakerIcon}"></path>
```

and re-compute it on volume change.

Hope this helps!
