### ISSUE TITLE
Internet Explorer 11?

### ISSUE THREAD

**Issue by StephenMeehan2016** [greghub/green-audio-player#8]
Hi, thanks for looking into and fixing the last issue I raised.

I've tested the player in Internet Explorer 11 (multiple-instance.html) and I've hit a compatibility issue. I was wondering if you could perhaps support IE 11?

Viewing the player in IE 11 triggers this error: `Object doesn't support property or method 'forEach'`

After a quick Google search I found a `'forEach'` fix for IE 11 on [StackOverflow](https://stackoverflow.com/questions/44652092/ie-doesnt-support-foreach-even-with-polyfill).

Adding this code 

```
// Function to make IE9+ support forEach:
        (function() {
            if (typeof NodeList.prototype.forEach === "function")
                return false;
            else
                NodeList.prototype.forEach = Array.prototype.forEach;
        })();  
```

inside the `<head>` before the green player script appears to fix the `forEach` problem -`forEach` error is no longer listed in debugger.

Unfortunately, another error is triggered:

`Object doesn't support property or method 'from'`

Is there any chance you could look into this?

**Comment by greghub** [comment]
Hi @StephenMeehan2016 , thanks for raising the issue. Please upgrade to version `1.0.8` and see if your issue is fixed. I've re-written several small parts of the code, so there shall not be problems with 'from' and 'forEach' now (no need for the 'forEach' polyfill)

**Comment by StephenMeehan2016** [comment]
Thanks for taking a look at this, really appreciate it.

I've dowloaded the latest version and tested `multiple-instance.html` in IE11

When I press play, I get the following error:

`SCRIPT5007: Unable to get property 'toString' of undefined or null reference
 File: green-audio-player.js, Line: 134, Column: 7`

When I scrub the audio, this error is triggered

`SCRIPT5022: IndexSizeError
File: green-audio-player.js, Line: 238, Column: 9`

Hope this helps to debug.

**Comment by greghub** [comment]
Hi @StephenMeehan2016 , today I finally managed to check the player on IE11 inside of an emulator, I've fixed the issues, so the IE compatibility has now been improved in version `1.0.9`

**Comment by StephenMeehan2016** [comment]
Hi,

That's great, thanks! I've also tested it - happy to report it's working perfect in IE 11!
