### ISSUE TITLE
Is it possible to use volume slider on mobile? 

### ISSUE THREAD

**Issue by Kcaden20** [greghub/green-audio-player#9]
I'd like to be able to change the volume of the player on mobile. I've got it to show on mobile but it doesn't work. Is there a way to make this possible? Or a place I can start with it?

**Comment by greghub** [comment]
Hi @Kcaden20 , unfortunately, it is not possible on iOS, as it does not let changing volume property programmatically. That's why I hide the volume controls on the iPhone and iPad, leaving users with the option to use volume buttons on the device.
